"""HZ-0C C8: real Python<->Rust FFI bridge correctness (reference/hz0c_pmetal_bridge.py).

Skips cleanly if the cdylib hasn't been built (`cargo build --release -p
hz0a-pmetal-bridge --manifest-path restart/hz0a_pmetal/Cargo.toml`),
matching this project's convention for real-artifact-gated tests (e.g.
the frozen-checkpoint-gated B6 test). Reuses
`restart/hz0a_pmetal/crates/hz0a-pmetal-kernel/tests/fixtures/conditional_attention_parity.json`
(generated by `scripts/hz0c_generate_pmetal_conditional_attention_fixture.py`
from the REAL Python `masked_anchor_attention` reference) rather than
building a new fixture -- this is the same cross-language ground truth
the Rust-side parity test already checks the CPU kernel against; here we
additionally check the Python ctypes MARSHALING layer on top of it.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from reference.hz0c_pmetal_bridge import (
    PMetalBridgeUnavailable, _library_path, conditional_attention_backward, conditional_attention_forward,
)

FIXTURE = Path("restart/hz0a_pmetal/crates/hz0a-pmetal-kernel/tests/fixtures/conditional_attention_parity.json")

try:
    _library_path()
    _BRIDGE_BUILT = True
except PMetalBridgeUnavailable:
    _BRIDGE_BUILT = False

pytestmark = pytest.mark.skipif(
    not _BRIDGE_BUILT or not FIXTURE.exists(),
    reason="PMetal bridge cdylib not built, or fixture missing -- run "
           "`cargo build --release -p hz0a-pmetal-bridge --manifest-path restart/hz0a_pmetal/Cargo.toml` "
           "and `PYTHONPATH=. python scripts/hz0c_generate_pmetal_conditional_attention_fixture.py`",
)


def _fixture() -> dict:
    return json.loads(FIXTURE.read_text())


def test_ffi_forward_matches_real_python_reference():
    data = _fixture()
    cfg = data["config"]
    batch, seq, dim, heads = cfg["batch"], cfg["seq"], cfg["dim"], cfg["heads"]
    x = np.array(data["x"], dtype=np.float32).reshape(batch, seq, dim)
    qkv_w = np.array(data["qkv_weight"], dtype=np.float32).reshape(3 * dim, dim)
    qkv_b = np.array(data["qkv_bias"], dtype=np.float32)
    out_w = np.array(data["out_weight"], dtype=np.float32).reshape(dim, dim)
    out_b = np.array(data["out_bias"], dtype=np.float32)
    trigger = np.array(data["trigger"], dtype=np.float32).reshape(batch, seq)
    expected = np.array(data["output"], dtype=np.float32).reshape(batch, seq, dim)

    output = conditional_attention_forward(x, trigger, qkv_w=qkv_w, qkv_b=qkv_b, out_w=out_w, out_b=out_b, heads=heads)
    max_diff = float(np.max(np.abs(output - expected)))
    assert max_diff < 1e-3, f"FFI forward diff vs real Python reference too large: {max_diff}"


def test_ffi_backward_matches_real_python_reference():
    data = _fixture()
    cfg = data["config"]
    batch, seq, dim, heads = cfg["batch"], cfg["seq"], cfg["dim"], cfg["heads"]
    x = np.array(data["x"], dtype=np.float32).reshape(batch, seq, dim)
    qkv_w = np.array(data["qkv_weight"], dtype=np.float32).reshape(3 * dim, dim)
    qkv_b = np.array(data["qkv_bias"], dtype=np.float32)
    out_w = np.array(data["out_weight"], dtype=np.float32).reshape(dim, dim)
    trigger = np.array(data["trigger"], dtype=np.float32).reshape(batch, seq)
    grad_output = np.array(data["grad_output"], dtype=np.float32).reshape(batch, seq, dim)

    grads = conditional_attention_backward(x, trigger, grad_output, qkv_w=qkv_w, qkv_b=qkv_b, out_w=out_w, heads=heads)
    checks = [
        ("grad_x", grads["grad_x"].reshape(-1), np.array(data["grad_x"], dtype=np.float32)),
        ("grad_qkv_weight", grads["grad_qkv_weight"].reshape(-1), np.array(data["grad_qkv_weight"], dtype=np.float32)),
        ("grad_qkv_bias", grads["grad_qkv_bias"], np.array(data["grad_qkv_bias"], dtype=np.float32)),
        ("grad_out_weight", grads["grad_out_weight"].reshape(-1), np.array(data["grad_out_weight"], dtype=np.float32)),
        ("grad_out_bias", grads["grad_out_bias"], np.array(data["grad_out_bias"], dtype=np.float32)),
    ]
    for name, actual, expected in checks:
        max_diff = float(np.max(np.abs(actual - expected)))
        assert max_diff < 1e-2, f"{name} FFI diff vs real Python reference too large: {max_diff}"


def test_ffi_forward_rejects_shape_mismatch_before_touching_ffi():
    """The Rust side trusts declared shapes and cannot itself detect an
    undersized buffer (a bare pointer carries no length) -- this must be
    caught in Python, BEFORE any pointer crosses the FFI boundary, or an
    undersized array would risk an out-of-bounds read on the Rust side."""
    x = np.zeros((1, 2, 4), dtype=np.float32)
    trigger = np.zeros((1, 2), dtype=np.float32)
    bad_qkv_w = np.zeros((1, 1), dtype=np.float32)  # wrong shape
    with pytest.raises(ValueError):
        conditional_attention_forward(x, trigger, qkv_w=bad_qkv_w, qkv_b=np.zeros(12, dtype=np.float32), out_w=np.zeros((4, 4), dtype=np.float32), out_b=np.zeros(4, dtype=np.float32), heads=2)
