"""Cross-language parity for the B10 Rust/ctypes bridge
(`restart/hz0a_pmetal/python/hz0b_memory_bridge.py`), called from real
Python -- not just Rust-native tests (`tests/parity.rs` already covers
those). Replays the SAME 12-step fixture used by `tests/parity.rs`
(`restart/hz0a_pmetal/crates/hz0b-pmetal-memory/tests/fixture.json`,
generated by `scripts/hz0b_generate_rust_parity_fixture.py` from the
actual Python reference) through the ctypes bridge and asserts exact
numeric agreement -- the same fixture, now proving the FULL round trip
(Python -> ctypes -> Rust -> ctypes -> Python) matches, not just the
Rust-internal replay.

Skips (not fails) if the bridge's cdylib hasn't been built -- this
module has no hard dependency on a Rust toolchain being present.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pytest

_BRIDGE_PYTHON_DIR = Path(__file__).resolve().parents[2] / "restart" / "hz0a_pmetal" / "python"
_FIXTURE_PATH = Path(__file__).resolve().parents[2] / "restart" / "hz0a_pmetal" / "crates" / "hz0b-pmetal-memory" / "tests" / "fixture.json"

sys.path.insert(0, str(_BRIDGE_PYTHON_DIR))

try:
    import hz0b_memory_bridge as bridge
    _BRIDGE_AVAILABLE = True
except (FileNotFoundError, OSError):
    _BRIDGE_AVAILABLE = False

pytestmark = pytest.mark.skipif(not _BRIDGE_AVAILABLE, reason="hz0b-pmetal-memory-bridge cdylib not built (cargo build --release -p hz0b-pmetal-memory-bridge)")


def _load_fixture() -> dict:
    return json.loads(_FIXTURE_PATH.read_text(encoding="utf-8"))


def test_bridge_replays_the_python_reference_fixture_exactly():
    fixture = _load_fixture()
    num_slots, key_dim, value_dim = fixture["num_slots"], fixture["key_dim"], fixture["value_dim"]
    state = bridge.reset(1, num_slots, key_dim, value_dim)

    for step in fixture["steps"]:
        op = step["op"]
        if op == "write":
            key = np.array(step["key"], dtype=np.float32)
            value = np.array(step["value"], dtype=np.float32)
            strength = np.array([step["strength"]], dtype=np.float32)
            slot_idx = np.array(step["slot_idx"], dtype=np.int32) if step["slot_idx"] is not None else None
            state, result_slot, rejected = bridge.write(state, key, value, strength, step=step["step"], source=step["source"], slot_idx=slot_idx)
            assert result_slot.tolist() == step["result_slot"]
            assert rejected.tolist() == step["rejected"]
        elif op == "read":
            query = np.array(step["query"], dtype=np.float32)
            readout, weights = bridge.read(state, query, hard=step["hard"], confidence_weighted=step["confidence_weighted"])
            assert np.allclose(readout, np.array(step["readout"], dtype=np.float32), atol=1e-4)
            assert np.allclose(weights, np.array(step["weights"], dtype=np.float32), atol=1e-4)
        elif op == "protect":
            slot_idx = np.array(step["slot_idx"], dtype=np.int32)
            strength = np.array([step["strength"]], dtype=np.float32)
            state = bridge.protect(state, slot_idx, strength)
        elif op == "update":
            slot_idx = np.array(step["slot_idx"], dtype=np.int32)
            new_value = np.array(step["new_value"], dtype=np.float32)
            state = bridge.update(state, slot_idx, new_value)
        elif op == "forget_or_decay":
            state = bridge.forget_or_decay(state, decay_rate=step["decay_rate"])
        else:
            raise AssertionError(f"unhandled fixture op: {op}")

    final = fixture["final_state"]
    assert np.allclose(state.keys, np.array(final["keys"], dtype=np.float32), atol=1e-4)
    assert np.allclose(state.values, np.array(final["values"], dtype=np.float32), atol=1e-4)
    assert np.allclose(state.confidence, np.array(final["confidence"], dtype=np.float32), atol=1e-4)
    assert np.allclose(state.protection, np.array(final["protection"], dtype=np.float32), atol=1e-4)

    key_dim_n = fixture["key_dim"]
    key_a = np.zeros((1, key_dim_n), dtype=np.float32); key_a[0, 0] = 1.0
    key_b = np.zeros((1, key_dim_n), dtype=np.float32); key_b[0, 1] = 1.0
    readout_a, _ = bridge.read(state, key_a, hard=True)
    readout_b, _ = bridge.read(state, key_b, hard=True)
    assert np.allclose(readout_a, np.array(fixture["final_readout_a"], dtype=np.float32), atol=1e-4)
    assert np.allclose(readout_b, np.array(fixture["final_readout_b"], dtype=np.float32), atol=1e-4)


def test_bridge_matches_live_python_reference_on_a_fresh_sequence():
    """Independent of the frozen fixture -- runs a NEW sequence through
    both the live Python/MLX reference and the bridge in the same test
    process, catching any drift between them that a stale fixture could
    hide."""
    import mlx.core as mx

    from reference.hz0b_memory_simulator import forget_or_decay as py_decay
    from reference.hz0b_memory_simulator import protect as py_protect
    from reference.hz0b_memory_simulator import read as py_read
    from reference.hz0b_memory_simulator import reset as py_reset
    from reference.hz0b_memory_simulator import write as py_write

    num_slots, key_dim, value_dim = 8, 6, 6
    py_state = py_reset(1, num_slots, key_dim, value_dim)
    rs_state = bridge.reset(1, num_slots, key_dim, value_dim)

    rng = np.random.default_rng(1234)
    for step in range(6):
        key_np = rng.standard_normal((1, key_dim)).astype(np.float32)
        value_np = rng.standard_normal((1, value_dim)).astype(np.float32)
        strength_np = np.array([0.9], dtype=np.float32)

        py_state, py_slot, py_rejected = py_write(py_state, mx.array(key_np), mx.array(value_np), mx.array(strength_np), step=step, source=1)
        rs_state, rs_slot, rs_rejected = bridge.write(rs_state, key_np, value_np, strength_np, step=step, source=1)
        assert np.array(py_slot).tolist() == rs_slot.tolist()
        assert np.array(py_rejected).tolist() == rs_rejected.tolist()

        if step == 3:
            py_state = py_protect(py_state, py_slot, mx.array([1.0]))
            rs_state = bridge.protect(rs_state, rs_slot, np.array([1.0], dtype=np.float32))
        if step == 5:
            py_state = py_decay(py_state, decay_rate=0.8)
            rs_state = bridge.forget_or_decay(rs_state, decay_rate=0.8)

    py_readout, py_weights = py_read(py_state, mx.array(key_np), hard=True)
    rs_readout, rs_weights = bridge.read(rs_state, key_np, hard=True)
    assert np.allclose(np.array(py_readout), rs_readout, atol=1e-4)
    assert np.allclose(np.array(py_weights), rs_weights, atol=1e-4)
    assert np.allclose(np.array(py_state.confidence), rs_state.confidence, atol=1e-4)
    assert np.allclose(np.array(py_state.protection), rs_state.protection, atol=1e-4)
