//! Cross-language parity: replays the EXACT operation sequence recorded
//! in `fixture.json` (generated by `scripts/hz0b_generate_rust_parity_fixture.py`
//! from the real Python reference, `reference/hz0b_memory_simulator.py`)
//! through this Rust port, and asserts the results agree -- the same
//! pattern `hz0a-pmetal-tensor`'s own parity test already established in
//! this workspace for HZ-0A's model code.

use hz0b_pmetal_memory::*;
use serde_json::Value;

/// Recursively flattens an arbitrarily-nested JSON array of numbers into
/// a flat Vec<f32> -- handles both 2D fields (key/value/readout, shape
/// [batch, dim]) and 3D fields (final_state.keys, shape
/// [batch, num_slots, dim]) uniformly, matching row-major flat-buffer
/// order either way.
fn flatten(v: &Value) -> Vec<f32> {
    match v {
        Value::Array(items) => items.iter().flat_map(flatten).collect(),
        Value::Number(n) => vec![n.as_f64().expect("numeric JSON value") as f32],
        other => panic!("flatten: unexpected JSON value {other:?}"),
    }
}

fn flatten_i32(v: &Value) -> Vec<i32> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_i64().unwrap() as i32)
        .collect()
}

fn assert_close(name: &str, a: &[f32], b: &[f32]) {
    assert_eq!(a.len(), b.len(), "{name}: length mismatch");
    for (i, (x, y)) in a.iter().zip(b.iter()).enumerate() {
        assert!((x - y).abs() < 1e-4, "{name}[{i}]: rust={x} python={y}");
    }
}

#[test]
fn replays_the_python_reference_fixture_exactly() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixture.json")).expect("fixture.json must parse");
    let num_slots = fixture["num_slots"].as_u64().unwrap() as usize;
    let key_dim = fixture["key_dim"].as_u64().unwrap() as usize;
    let value_dim = fixture["value_dim"].as_u64().unwrap() as usize;

    let mut state = reset(1, num_slots, key_dim, value_dim);

    for step in fixture["steps"].as_array().unwrap() {
        match step["op"].as_str().unwrap() {
            "write" => {
                let key = flatten(&step["key"]);
                let value = flatten(&step["value"]);
                let strength = step["strength"].as_f64().unwrap() as f32;
                let step_num = step["step"].as_i64().unwrap() as i32;
                let source = step["source"].as_i64().unwrap() as i32;
                let slot_idx = if step["slot_idx"].is_null() {
                    None
                } else {
                    Some(flatten_i32(&step["slot_idx"]))
                };
                let (new_state, result_slot, rejected) = write(
                    &state,
                    &key,
                    &value,
                    &[strength],
                    step_num,
                    source,
                    slot_idx.as_deref(),
                );
                state = new_state;
                assert_eq!(
                    result_slot,
                    flatten_i32(&step["result_slot"]),
                    "write result_slot mismatch"
                );
                let expected_rejected: Vec<bool> = step["rejected"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_bool().unwrap())
                    .collect();
                assert_eq!(rejected, expected_rejected, "write rejected mismatch");
            }
            "read" => {
                let query = flatten(&step["query"]);
                let hard = step["hard"].as_bool().unwrap();
                let confidence_weighted = step["confidence_weighted"].as_bool().unwrap();
                let (readout, weights) = read(&state, &query, None, hard, confidence_weighted);
                assert_close("read.readout", &readout, &flatten(&step["readout"]));
                assert_close("read.weights", &weights, &flatten(&step["weights"]));
            }
            "protect" => {
                let slot_idx = flatten_i32(&step["slot_idx"]);
                let strength = step["strength"].as_f64().unwrap() as f32;
                state = protect(&state, &slot_idx, &[strength]);
            }
            "update" => {
                let slot_idx = flatten_i32(&step["slot_idx"]);
                let new_value = flatten(&step["new_value"]);
                state = update(&state, &slot_idx, &new_value);
            }
            "forget_or_decay" => {
                let decay_rate = step["decay_rate"].as_f64().unwrap() as f32;
                state = forget_or_decay(&state, decay_rate);
            }
            other => panic!("unhandled fixture op: {other}"),
        }
    }

    let final_state = &fixture["final_state"];
    assert_close("final keys", &state.keys, &flatten(&final_state["keys"]));
    assert_close(
        "final values",
        &state.values,
        &flatten(&final_state["values"]),
    );
    assert_close(
        "final confidence",
        &state.confidence,
        &flatten(&final_state["confidence"]),
    );
    assert_close(
        "final protection",
        &state.protection,
        &flatten(&final_state["protection"]),
    );

    // key_a is index 0 in the fixture's key space (onehot(KEY_DIM, 0)),
    // key_b is index 1.
    let key_a: Vec<f32> = (0..key_dim)
        .map(|i| if i == 0 { 1.0 } else { 0.0 })
        .collect();
    let key_b: Vec<f32> = (0..key_dim)
        .map(|i| if i == 1 { 1.0 } else { 0.0 })
        .collect();
    let (final_readout_a, _) = read(&state, &key_a, None, true, true);
    let (final_readout_b, _) = read(&state, &key_b, None, true, true);
    assert_close(
        "final_readout_a",
        &final_readout_a,
        &flatten(&fixture["final_readout_a"]),
    );
    assert_close(
        "final_readout_b",
        &final_readout_b,
        &flatten(&fixture["final_readout_b"]),
    );
}
