//! Cross-language parity: loads the exact parameter values the Python
//! `restart/hz0a_pmetal/python/native_model.py` reference used (generated by
//! `scripts/hz0a_generate_rust_parity_fixture.py`), runs the same tokens
//! through the Rust `TinyModel`, and checks logits/loss/gradients agree.
//! This is the direct evidence for A6's exit gate ("PMetal and the simple
//! reference agree ... on block outputs, logits, loss, gradients").

use hz0a_pmetal_tensor::{AdamW, TinyModel};
use serde_json::Value;

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/tiny_model_parity.json");
    let text = std::fs::read_to_string(path).expect("run scripts/hz0a_generate_rust_parity_fixture.py first");
    serde_json::from_str(&text).expect("fixture must be valid JSON")
}

fn f64_vec(value: &Value) -> Vec<f64> {
    value.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect()
}

fn usize_vec(value: &Value) -> Vec<usize> {
    value.as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as usize).collect()
}

#[test]
fn tiny_model_matches_python_reference_forward_and_backward() {
    let data = fixture();
    let config = &data["config"];
    let vocab = config["vocab"].as_u64().unwrap() as usize;
    let dim = config["dim"].as_u64().unwrap() as usize;
    let heads = config["heads"].as_u64().unwrap() as usize;
    let d_k = config["d_k"].as_u64().unwrap() as usize;
    let d_v = config["d_v"].as_u64().unwrap() as usize;
    let d_ff = config["d_ff"].as_u64().unwrap() as usize;
    let layers = config["layers"].as_u64().unwrap() as usize;
    let attention_indices = usize_vec(&config["attention_indices"]);

    let mut model = TinyModel::new(vocab, dim, heads, d_k, d_v, d_ff, &attention_indices, layers, 0);

    let flat_parameters = f64_vec(&data["flat_parameters"]);
    model.load_flat_parameters(&flat_parameters);

    let token_ids = usize_vec(&data["token_ids"]);
    let targets = usize_vec(&data["targets"]);

    let logits = model.forward(&token_ids);
    let expected_logits = f64_vec(&data["logits"]);
    assert_eq!(logits.len(), expected_logits.len());
    let mut max_logit_error = 0.0f64;
    for (rust_val, python_val) in logits.iter().zip(expected_logits.iter()) {
        max_logit_error = max_logit_error.max((*rust_val as f64 - python_val).abs());
    }
    assert!(max_logit_error < 1e-3, "max logit error {max_logit_error} too large");

    model.zero_grad();
    let loss = model.loss_and_backward(&token_ids, &targets);
    let expected_loss = data["loss"].as_f64().unwrap();
    assert!((loss as f64 - expected_loss).abs() < 1e-3, "loss mismatch: rust={loss} python={expected_loss}");

    let gradients = model.flat_gradients();
    let expected_gradients = f64_vec(&data["flat_gradients"]);
    assert_eq!(gradients.len(), expected_gradients.len());
    let mut max_grad_error = 0.0f64;
    let mut max_grad_index = 0usize;
    for (index, (rust_val, python_val)) in gradients.iter().zip(expected_gradients.iter()).enumerate() {
        let error = (rust_val - python_val).abs();
        if error > max_grad_error {
            max_grad_error = error;
            max_grad_index = index;
        }
    }
    assert!(
        max_grad_error < 1e-2,
        "max gradient error {max_grad_error} at index {max_grad_index} (rust={}, python={})",
        gradients[max_grad_index],
        expected_gradients[max_grad_index]
    );

    // One optimizer update: same AdamW math (lr=1e-4, weight_decay=0.0),
    // applied to the same gradients just computed -- closes A6's "...and
    // one optimizer update" exit-gate clause with real cross-language
    // agreement, not just a same-language self-check.
    let adamw_config = &data["adamw_config"];
    let lr = adamw_config["learning_rate"].as_f64().unwrap() as f32;
    let weight_decay = adamw_config["weight_decay"].as_f64().unwrap() as f32;
    let mut optimizer = AdamW::new_with_weight_decay(lr, weight_decay);
    optimizer.update(&mut model.parameters_mut());
    let updated: Vec<f64> = model.parameters_mut().iter().flat_map(|p| p.data.iter().map(|&v| v as f64)).collect();
    let expected_updated = f64_vec(&data["updated_parameters_after_one_adamw_step"]);
    assert_eq!(updated.len(), expected_updated.len());
    let mut max_param_error = 0.0f64;
    for (rust_val, python_val) in updated.iter().zip(expected_updated.iter()) {
        max_param_error = max_param_error.max((rust_val - python_val).abs());
    }
    assert!(max_param_error < 1e-3, "max post-AdamW parameter error {max_param_error} too large");
}
