[workspace]
members = [
  "crates/hz0a-pmetal-kernel",
  "crates/hz0a-pmetal-bridge",
  "crates/hz0a-pmetal-tensor",
  "crates/hz0a-pmetal-gpu",
  "crates/hz0b-pmetal-memory",
  "crates/hz0b-pmetal-memory-bridge",
  "crates/hz0d-pmetal-fastweights",
  "crates/hz0d-pmetal-fastweights-bridge",
  "crates/hz0e-pmetal-moe"
]

resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"
authors = ["Ishaan Gubbala"]
